title: Margot Neyret
email: margot@neyret.me
description: 'Margot Neyret - Researcher - Laboratory for Mountain Ecosystem and Societies (LESSEM) - INRAE - France'
baseurl: ''
url: ''
twitter_username: ''
github_username: mneyret
markdown: kramdown
plugins:
  - jekyll-admin
kramdown:
  parse_block_html: true
